import { ImageResponse } from "next/og";

// PWA + favicon icon, generated by Next at build time.
// Riffs on the Logo component's four-dot mark using the official GDG palette.

export const size = { width: 512, height: 512 };
export const contentType = "image/png";

export default function Icon() {
  return new ImageResponse(
    <div
      style={{
        width: "100%",
        height: "100%",
        background: "#ffffff",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
      }}
    >
      <svg
        width="360"
        height="360"
        viewBox="0 0 360 360"
        xmlns="http://www.w3.org/2000/svg"
      >
        <circle cx="80" cy="180" r="40" fill="#4285f4" />
        <circle cx="148" cy="120" r="40" fill="#ea4335" />
        <circle cx="212" cy="120" r="40" fill="#f9ab00" />
        <circle cx="280" cy="180" r="40" fill="#34a853" />
        <path
          d="M 60 250 Q 180 320, 300 250"
          stroke="#1e1e1e"
          strokeWidth="22"
          fill="none"
          strokeLinecap="round"
        />
      </svg>
    </div>,
    size,
  );
}
