import type { EventDetail, EventSummary } from "./types";

export const COPY = {
  es: {
    nav: {
      home: "Inicio",
      events: "Eventos",
      community: "Comunidad",
      about: "Sobre nosotros",
      join: "Únete",
    },
    hero: {
      eyebrow: "Comunidad de desarrolladores · Guayaquil, Ecuador",
      title: "Construimos lo que viene\npara la web del Pacífico.",
      sub: "Somos GDG Guayaquil. Reunimos a quienes diseñan, programan y enseñan tecnología en la costa del Ecuador. Eventos en vivo, talleres, comunidad.",
      ctaPrimary: "Ver próximos eventos",
      ctaSecondary: "Conocer la comunidad",
      stat1: "Miembros activos",
      stat2: "Eventos al año",
      stat3: "Años organizando",
    },
    upcoming: {
      eyebrow: "Calendario 2026",
      title: "Próximos eventos",
      sub: "Dos encuentros insignia este año, además de meetups mensuales gratuitos.",
      viewAll: "Ver todos los eventos",
      details: "Detalles del evento",
    },
    about: {
      eyebrow: "Sobre nosotros",
      title: "Una comunidad técnica abierta, en la mitad del mundo.",
      body: "GDG Guayaquil es un capítulo independiente del programa Google Developer Groups. Operamos desde 2017 organizando charlas, talleres y hackatones para más de 3,200 desarrolladores en la región. Sin barreras: español primario, inglés cuando ayuda, código abierto siempre.",
      pillarTitle1: "Aprendizaje práctico",
      pillarBody1:
        "Talleres con código en vivo, no diapositivas. Salimos con algo construido.",
      pillarTitle2: "Mentoría comunitaria",
      pillarBody2:
        "Devs senior emparejados con quienes están empezando. Trimestralmente.",
      pillarTitle3: "Tecnología abierta",
      pillarBody3:
        "Priorizamos herramientas y modelos de licencia que la comunidad puede adoptar.",
    },
    footer: {
      tagline: "Construyendo en la costa del Pacífico desde 2017.",
      navTitle: "Plataforma",
      eventsTitle: "Eventos",
      connectTitle: "Conectar",
      newsletter: "Recibe el boletín",
      newsletterSub:
        "Anuncios de eventos y oportunidades. Una vez al mes, sin spam.",
      subscribe: "Suscribirse",
      emailPlaceholder: "tu@correo.com",
      legal: "© 2026 GDG Guayaquil. Capítulo comunitario independiente.",
    },
    eventDetail: {
      back: "Todos los eventos",
      addCalendar: "Agregar al calendario",
      getTickets: "Conseguir entrada",
      countdown: { d: "Días", h: "Horas", m: "Min", s: "Seg" },
      sections: {
        agenda: "Agenda",
        speakers: "Speakers",
        sponsors: "Sponsors",
        venue: "Venue",
        faq: "FAQ",
      },
      agendaSub: "Programa preliminar. Salones y horarios pueden cambiar.",
      speakersSub: "Voces locales y regionales construyendo en producción.",
      sponsorsSub: "Hacen posible que el evento sea gratuito o de bajo costo.",
      sponsorsTier: {
        platinum: "Platinum",
        gold: "Gold",
        silver: "Silver",
        community: "Community",
      },
      venueSub:
        "Auditorio principal con capacidad para 600 asistentes y 4 salas paralelas.",
      faqSub: "Lo que preguntan más a menudo.",
      becomeSponsor: "Quiero ser sponsor",
    },
    eventsPage: {
      title: "Calendario completo",
      sub: "Tres eventos insignia confirmados para 2026, además de meetups mensuales y noches de código.",
      filterAll: "Todos",
      details: "Detalles",
    },
  },
  en: {
    nav: {
      home: "Home",
      events: "Events",
      community: "Community",
      about: "About",
      join: "Join",
    },
    hero: {
      eyebrow: "Developer community · Guayaquil, Ecuador",
      title: "Building what comes next\nfor the Pacific coast.",
      sub: "We are GDG Guayaquil. We bring together the people designing, coding and teaching technology along the Ecuadorian coast. Live events, workshops, community.",
      ctaPrimary: "See upcoming events",
      ctaSecondary: "Meet the community",
      stat1: "Active members",
      stat2: "Events per year",
      stat3: "Years running",
    },
    upcoming: {
      eyebrow: "Calendar 2026",
      title: "Upcoming events",
      sub: "Two flagship events this year, plus free monthly meetups.",
      viewAll: "See all events",
      details: "Event details",
    },
    about: {
      eyebrow: "About",
      title: "An open technical community, on the equator.",
      body: "GDG Guayaquil is an independent chapter of the Google Developer Groups program. Since 2017 we have organized talks, workshops and hackathons for over 3,200 developers across the region. No barriers: Spanish primary, English when it helps, open source always.",
      pillarTitle1: "Practical learning",
      pillarBody1:
        "Workshops with live code, not slides. You leave having built something.",
      pillarTitle2: "Community mentorship",
      pillarBody2:
        "Senior devs paired with people just starting. Quarterly cohorts.",
      pillarTitle3: "Open technology",
      pillarBody3:
        "We prioritize tools and license models the community can actually adopt.",
    },
    footer: {
      tagline: "Building on the Pacific coast since 2017.",
      navTitle: "Platform",
      eventsTitle: "Events",
      connectTitle: "Connect",
      newsletter: "Get the newsletter",
      newsletterSub:
        "Event announcements and opportunities. Once a month, no spam.",
      subscribe: "Subscribe",
      emailPlaceholder: "you@email.com",
      legal: "© 2026 GDG Guayaquil. Independent community chapter.",
    },
    eventDetail: {
      back: "All events",
      addCalendar: "Add to calendar",
      getTickets: "Get tickets",
      countdown: { d: "Days", h: "Hours", m: "Min", s: "Sec" },
      sections: {
        agenda: "Agenda",
        speakers: "Speakers",
        sponsors: "Sponsors",
        venue: "Venue",
        faq: "FAQ",
      },
      agendaSub: "Preliminary schedule. Rooms and times subject to change.",
      speakersSub: "Local and regional voices building in production.",
      sponsorsSub: "They make it possible to keep the event free or low-cost.",
      sponsorsTier: {
        platinum: "Platinum",
        gold: "Gold",
        silver: "Silver",
        community: "Community",
      },
      venueSub: "Main auditorium for 600 attendees plus 4 parallel rooms.",
      faqSub: "The questions we get most often.",
      becomeSponsor: "Become a sponsor",
    },
    eventsPage: {
      title: "Full calendar",
      sub: "Three flagship events confirmed for 2026, plus monthly meetups and code nights.",
      filterAll: "All",
      details: "Details",
    },
  },
} as const;

export const EVENTS: EventSummary[] = [
  {
    id: "e1",
    slug: "bwai-2026",
    name: "Build with AI",
    type: "build_with_ai",
    year: 2026,
    status: "published",
    accent: "blue",
    start_at: new Date("2026-05-23T09:00:00-05:00"),
    end_at: new Date("2026-05-23T19:00:00-05:00"),
    timezone: "GYE",
    venue_name: "ESPOL — Centro de Convenciones",
    venue_short: "ESPOL · Campus Gustavo Galindo",
    venue_address: "Km 30.5 Vía Perimetral, Guayaquil",
    ticket_url: "#tickets",
    leaderboard_enabled: true,
    summary_es:
      "Un día construyendo con modelos generativos: Gemini, fine-tuning, agentes y producción.",
    summary_en:
      "One day building with generative models: Gemini, fine-tuning, agents, and production.",
    expected: "450+",
  },
  {
    id: "e2",
    slug: "devfest-2026",
    name: "DevFest",
    type: "devfest",
    year: 2026,
    status: "published",
    accent: "green",
    start_at: new Date("2026-11-14T08:30:00-05:00"),
    end_at: new Date("2026-11-14T20:00:00-05:00"),
    timezone: "GYE",
    venue_name: "Universidad Casa Grande — Auditorio",
    venue_short: "Universidad Casa Grande",
    venue_address: "Av. Las Palmas 304, Guayaquil",
    ticket_url: "#tickets",
    leaderboard_enabled: true,
    summary_es:
      "El festival anual de la comunidad. Cuatro tracks, talleres en paralelo y más de 30 sesiones.",
    summary_en:
      "The community's annual festival. Four tracks, parallel workshops, and 30+ sessions.",
    expected: "800+",
  },
  {
    id: "e3",
    slug: "io-extended-2026",
    name: "I/O Extended",
    type: "google_io",
    year: 2026,
    status: "published",
    accent: "yellow",
    start_at: new Date("2026-06-20T14:00:00-05:00"),
    end_at: new Date("2026-06-20T20:00:00-05:00"),
    timezone: "GYE",
    venue_name: "Innopolis Hub",
    venue_short: "Innopolis Hub",
    venue_address: "Cdla. Kennedy Norte, Guayaquil",
    ticket_url: "#tickets",
    leaderboard_enabled: false,
    summary_es:
      "Repaso comunitario de I/O 2026: lo más relevante para devs, en formato charla + lightning talks.",
    summary_en:
      "Community recap of I/O 2026: what matters for devs, in talk + lightning-talk format.",
    expected: "180",
  },
];

export const EVENT_DETAIL: Record<string, EventDetail> = {
  "bwai-2026": {
    hero: {
      tagline_es: "Construye con modelos. Mide en producción.",
      tagline_en: "Build with models. Measure in production.",
      lede_es:
        "Un sábado completo dedicado a llevar IA generativa más allá del demo: arquitectura, costos, evals y entrega real. Con speakers de Ecuador, Colombia y Perú.",
      lede_en:
        "A full Saturday dedicated to taking generative AI past the demo: architecture, cost, evals, and real shipping. Speakers from Ecuador, Colombia, and Peru.",
    },
    agenda: [
      {
        time: "09:00",
        dur: 30,
        title_es: "Registro y desayuno",
        title_en: "Check-in & breakfast",
        track: null,
        room: "Lobby",
      },
      {
        time: "09:30",
        dur: 30,
        title_es: "Bienvenida + estado del capítulo",
        title_en: "Welcome + chapter update",
        track: "Plenaria",
        room: "Auditorio A",
      },
      {
        time: "10:00",
        dur: 50,
        title_es: "Keynote: Agentes en producción, lecciones de un año",
        title_en: "Keynote: Agents in production, a year of lessons",
        track: "Plenaria",
        room: "Auditorio A",
        speaker: "María Cabrera",
      },
      {
        time: "11:00",
        dur: 45,
        title_es: "Workshop: Gemini API + tool use desde cero",
        title_en: "Workshop: Gemini API + tool use from scratch",
        track: "Hands-on",
        room: "Sala 1",
        speaker: "Diego Salinas",
      },
      {
        time: "11:00",
        dur: 45,
        title_es: "Talk: Evals que no mienten",
        title_en: "Talk: Evals that don't lie",
        track: "AI Engineering",
        room: "Auditorio A",
        speaker: "Lucía Vega",
      },
      {
        time: "12:00",
        dur: 60,
        title_es: "Almuerzo + networking",
        title_en: "Lunch + networking",
        track: null,
        room: "Patio",
      },
      {
        time: "13:00",
        dur: 45,
        title_es: "Talk: RAG en español, lo que rompe",
        title_en: "Talk: RAG in Spanish, what breaks",
        track: "AI Engineering",
        room: "Auditorio A",
        speaker: "Andrés Pacheco",
      },
      {
        time: "13:00",
        dur: 45,
        title_es: "Workshop: Fine-tuning con Vertex AI",
        title_en: "Workshop: Fine-tuning with Vertex AI",
        track: "Hands-on",
        room: "Sala 1",
        speaker: "Camila Ruiz",
      },
      {
        time: "14:00",
        dur: 45,
        title_es: "Panel: Costos reales de IA en startups latam",
        title_en: "Panel: Real AI costs at LatAm startups",
        track: "Plenaria",
        room: "Auditorio A",
      },
      {
        time: "15:00",
        dur: 60,
        title_es: "Hackathon flash: agentes con propósito",
        title_en: "Flash hackathon: agents with purpose",
        track: "Hands-on",
        room: "Sala 1+2",
      },
      {
        time: "17:00",
        dur: 30,
        title_es: "Lightning talks comunitarias",
        title_en: "Community lightning talks",
        track: "Plenaria",
        room: "Auditorio A",
      },
      {
        time: "18:00",
        dur: 60,
        title_es: "Cierre + after en planta baja",
        title_en: "Closing + after-party downstairs",
        track: null,
        room: "Patio",
      },
    ],
    speakers: [
      {
        name: "María Cabrera",
        role_es: "Staff AI Eng · Mercado Libre",
        role_en: "Staff AI Eng · Mercado Libre",
        city: "Bogotá",
      },
      {
        name: "Diego Salinas",
        role_es: "GDE Cloud · Independiente",
        role_en: "GDE Cloud · Independent",
        city: "Quito",
      },
      {
        name: "Lucía Vega",
        role_es: "Senior ML Eng · Kushki",
        role_en: "Senior ML Eng · Kushki",
        city: "Guayaquil",
      },
      {
        name: "Andrés Pacheco",
        role_es: "Founding Eng · Truora",
        role_en: "Founding Eng · Truora",
        city: "Lima",
      },
      {
        name: "Camila Ruiz",
        role_es: "Customer Eng · Google Cloud",
        role_en: "Customer Eng · Google Cloud",
        city: "CDMX",
      },
      {
        name: "Joel Mendoza",
        role_es: "CTO · Banco Pichincha Labs",
        role_en: "CTO · Banco Pichincha Labs",
        city: "Guayaquil",
      },
      {
        name: "Valentina Soto",
        role_es: "Founder · evals.dev",
        role_en: "Founder · evals.dev",
        city: "Santiago",
      },
      {
        name: "Rafael Castro",
        role_es: "AI PM · Despegar",
        role_en: "AI PM · Despegar",
        city: "BA",
      },
    ],
    sponsors: {
      platinum: [{ name: "Banco Pichincha" }, { name: "Kushki" }],
      gold: [
        { name: "Pacifico Cloud" },
        { name: "Truora" },
        { name: "Despegar" },
      ],
      silver: [
        { name: "evals.dev" },
        { name: "Innopolis" },
        { name: "Aeris" },
        { name: "Forma.ai" },
      ],
      community: [
        { name: "ESPOL" },
        { name: "GDG Quito" },
        { name: "GDG Lima" },
        { name: "WTM Ecuador" },
        { name: "Laboratoria" },
        { name: "Platzi" },
      ],
    },
    faq: [
      {
        q_es: "¿Hay que saber programar para asistir?",
        q_en: "Do I need to know how to code to attend?",
        a_es: "Las charlas plenarias son accesibles para cualquier perfil técnico. Los workshops de la sala Hands-on requieren saber al menos un lenguaje (Python o JS recomendado) y traer laptop.",
        a_en: "The plenary talks are accessible to any technical profile. The Hands-on room workshops require at least one language (Python or JS recommended) and a laptop.",
      },
      {
        q_es: "¿El evento es gratuito?",
        q_en: "Is the event free?",
        a_es: "Hay tres categorías: Community (gratis, cupo limitado), Standard (USD 25, incluye almuerzo y kit) y Workshop Pass (USD 60, incluye plaza garantizada en talleres hands-on).",
        a_en: "Three categories: Community (free, limited spots), Standard (USD 25, includes lunch and kit), and Workshop Pass (USD 60, guaranteed spot in hands-on workshops).",
      },
      {
        q_es: "¿En qué idioma serán las charlas?",
        q_en: "What language will talks be in?",
        a_es: "Mayoritariamente en español. Speakers internacionales pueden presentar en inglés. No hay traducción simultánea.",
        a_en: "Mostly Spanish. International speakers may present in English. There is no simultaneous translation.",
      },
      {
        q_es: "¿Hay estacionamiento?",
        q_en: "Is parking available?",
        a_es: "ESPOL tiene estacionamiento gratuito de visitantes. Recomendamos llegar antes de las 8:45 para asegurar lugar. Hay parada de la Metrovía a 400m.",
        a_en: "ESPOL has free visitor parking. We recommend arriving before 8:45 to secure a spot. There is a Metrovía stop 400m away.",
      },
      {
        q_es: "¿Puedo presentar un lightning talk?",
        q_en: "Can I present a lightning talk?",
        a_es: "Sí. Abrimos 8 cupos comunitarios de 5 minutos cada uno. Postulación en el formulario hasta el 10 de mayo.",
        a_en: "Yes. We open 8 community slots of 5 minutes each. Apply via the form until May 10.",
      },
      {
        q_es: "¿Tendrá grabación?",
        q_en: "Will sessions be recorded?",
        a_es: "Las charlas de plenaria se publicarán en el canal de YouTube en las dos semanas siguientes. Los workshops no se graban.",
        a_en: "Plenary talks will be published on YouTube within two weeks. Workshops are not recorded.",
      },
    ],
  },
};

export function getEventBySlug(slug: string): EventSummary | undefined {
  return EVENTS.find((e) => e.slug === slug);
}

export function getEventDetail(slug: string): EventDetail | undefined {
  return EVENT_DETAIL[slug];
}
