// This file is regenerated by:
//   npm run supabase:types
// (which invokes `supabase gen types typescript --local`).
// Do not edit by hand — committed only as a placeholder until the local DB is running.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      events: {
        Row: {
          id: string;
          slug: string;
          name: string;
          type:
            | "devfest"
            | "build_with_ai"
            | "google_io"
            | "meetup"
            | "tech_talk"
            | "conference"
            | "workshop"
            | "hackathon";
          year: number;
          status: "draft" | "published" | "live" | "closed";
          language_mode: "es" | "en" | "bilingual";
          start_at: string;
          end_at: string;
          timezone: string;
          venue_name: string | null;
          venue_address: string | null;
          venue_map_url: string | null;
          ticket_url: string | null;
          pre_checkin_deadline: string | null;
          leaderboard_enabled: boolean;
          theme_key: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          type:
            | "devfest"
            | "build_with_ai"
            | "google_io"
            | "meetup"
            | "tech_talk"
            | "conference"
            | "workshop"
            | "hackathon";
          year: number;
          status?: "draft" | "published" | "live" | "closed";
          language_mode?: "es" | "en" | "bilingual";
          start_at: string;
          end_at: string;
          timezone?: string;
          venue_name?: string | null;
          venue_address?: string | null;
          venue_map_url?: string | null;
          ticket_url?: string | null;
          pre_checkin_deadline?: string | null;
          leaderboard_enabled?: boolean;
          theme_key?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["events"]["Insert"]>;
      };
      event_content: {
        Row: {
          event_id: string;
          hero: Json;
          agenda: Json;
          speakers: Json;
          sponsors: Json;
          gallery: Json;
          faq: Json;
          updated_at: string;
        };
        Insert: {
          event_id: string;
          hero?: Json;
          agenda?: Json;
          speakers?: Json;
          sponsors?: Json;
          gallery?: Json;
          faq?: Json;
          updated_at?: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["event_content"]["Insert"]
        >;
      };
    };
    Enums: {
      event_type:
        | "devfest"
        | "build_with_ai"
        | "google_io"
        | "meetup"
        | "tech_talk"
        | "conference"
        | "workshop"
        | "hackathon";
      event_status: "draft" | "published" | "live" | "closed";
      language_mode: "es" | "en" | "bilingual";
    };
  };
};
