// This file is regenerated by:
//   npm run supabase:types
// (which invokes `supabase gen types typescript --local`).
// Do not edit by hand — committed only as a placeholder until the local DB is running.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

type EventTypeEnum =
  | "devfest"
  | "build_with_ai"
  | "google_io"
  | "meetup"
  | "tech_talk"
  | "conference"
  | "workshop"
  | "hackathon";

type SystemRole = "attendee" | "organizer" | "admin";
type PreCheckinStatus = "not_submitted" | "pending" | "approved" | "rejected";
type ScanTargetType = "sponsor" | "activity" | "attendee";
type ScanResult = "accepted" | "rejected";
type PointSource =
  | "sponsor"
  | "activity"
  | "networking"
  | "bonus"
  | "admin_adjustment";

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "12";
  };
  public: {
    Tables: {
      events: {
        Row: {
          id: string;
          slug: string;
          name: string;
          type: EventTypeEnum;
          year: number;
          status: "draft" | "published" | "live" | "closed";
          language_mode: "es" | "en" | "bilingual";
          start_at: string;
          end_at: string;
          timezone: string;
          venue_name: string | null;
          venue_address: string | null;
          venue_map_url: string | null;
          ticket_url: string | null;
          pre_checkin_deadline: string | null;
          leaderboard_enabled: boolean;
          theme_key: string;
          summary_es: string | null;
          summary_en: string | null;
          expected_attendance: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          type: EventTypeEnum;
          year: number;
          status?: "draft" | "published" | "live" | "closed";
          language_mode?: "es" | "en" | "bilingual";
          start_at: string;
          end_at: string;
          timezone?: string;
          venue_name?: string | null;
          venue_address?: string | null;
          venue_map_url?: string | null;
          ticket_url?: string | null;
          pre_checkin_deadline?: string | null;
          leaderboard_enabled?: boolean;
          theme_key?: string;
          summary_es?: string | null;
          summary_en?: string | null;
          expected_attendance?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["events"]["Insert"]>;
        Relationships: [];
      };
      event_content: {
        Row: {
          event_id: string;
          hero: Json;
          agenda: Json;
          speakers: Json;
          sponsors: Json;
          gallery: Json;
          faq: Json;
          updated_at: string;
        };
        Insert: {
          event_id: string;
          hero?: Json;
          agenda?: Json;
          speakers?: Json;
          sponsors?: Json;
          gallery?: Json;
          faq?: Json;
          updated_at?: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["event_content"]["Insert"]
        >;
        Relationships: [
          {
            foreignKeyName: "event_content_event_id_fkey";
            columns: ["event_id"];
            isOneToOne: true;
            referencedRelation: "events";
            referencedColumns: ["id"];
          },
        ];
      };
      users: {
        Row: {
          id: string;
          google_id: string | null;
          email: string;
          full_name: string;
          photo_url: string | null;
          company: string | null;
          role: string | null;
          phone: string | null;
          city: string | null;
          social_links: Json;
          system_role: SystemRole;
          accepted_terms_at: string | null;
          accepted_privacy_at: string | null;
          accepted_sponsor_consent_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          google_id?: string | null;
          email: string;
          full_name?: string;
          photo_url?: string | null;
          company?: string | null;
          role?: string | null;
          phone?: string | null;
          city?: string | null;
          social_links?: Json;
          system_role?: SystemRole;
          accepted_terms_at?: string | null;
          accepted_privacy_at?: string | null;
          accepted_sponsor_consent_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["users"]["Insert"]>;
        Relationships: [];
      };
      consent_records: {
        Row: {
          id: string;
          user_id: string;
          consent_type: string;
          version: string;
          accepted_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          consent_type: string;
          version?: string;
          accepted_at?: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["consent_records"]["Insert"]
        >;
        Relationships: [];
      };
      registrations: {
        Row: {
          id: string;
          event_id: string;
          user_id: string;
          pre_checkin_status: PreCheckinStatus;
          approved_at: string | null;
          total_points: number;
          event_rank: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          user_id: string;
          pre_checkin_status?: PreCheckinStatus;
          approved_at?: string | null;
          total_points?: number;
          event_rank?: number | null;
          created_at?: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["registrations"]["Insert"]
        >;
        Relationships: [];
      };
      sponsors: {
        Row: {
          id: string;
          event_id: string;
          name: string;
          tier: string | null;
          logo_url: string | null;
          description: string | null;
          booth_label: string | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          name: string;
          tier?: string | null;
          logo_url?: string | null;
          description?: string | null;
          booth_label?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["sponsors"]["Insert"]>;
        Relationships: [];
      };
      activities: {
        Row: {
          id: string;
          sponsor_id: string;
          event_id: string;
          name: string;
          points: number;
          starts_at: string | null;
          ends_at: string | null;
          qr_rotation_seconds: number;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          sponsor_id: string;
          event_id: string;
          name: string;
          points?: number;
          starts_at?: string | null;
          ends_at?: string | null;
          qr_rotation_seconds?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["activities"]["Insert"]>;
        Relationships: [];
      };
      scan_logs: {
        Row: {
          id: string;
          event_id: string;
          scanner_user_id: string;
          target_type: ScanTargetType;
          target_id: string;
          scanned_at: string;
          points_granted: number;
          result: ScanResult;
          reject_reason: string | null;
        };
        Insert: {
          id?: string;
          event_id: string;
          scanner_user_id: string;
          target_type: ScanTargetType;
          target_id: string;
          scanned_at?: string;
          points_granted?: number;
          result: ScanResult;
          reject_reason?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["scan_logs"]["Insert"]>;
        Relationships: [];
      };
      point_transactions: {
        Row: {
          id: string;
          event_id: string;
          user_id: string;
          source_type: PointSource;
          source_id: string | null;
          points: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          user_id: string;
          source_type: PointSource;
          source_id?: string | null;
          points: number;
          created_at?: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["point_transactions"]["Insert"]
        >;
        Relationships: [];
      };
    };
    Views: Record<never, never>;
    Functions: Record<never, never>;
    Enums: {
      event_type: EventTypeEnum;
      event_status: "draft" | "published" | "live" | "closed";
      language_mode: "es" | "en" | "bilingual";
      system_role: SystemRole;
      precheckin_status: PreCheckinStatus;
      scan_target_type: ScanTargetType;
      scan_result: ScanResult;
      point_source: PointSource;
    };
    CompositeTypes: Record<never, never>;
  };
};
