// This file is regenerated by:
//   npm run supabase:types
// (which invokes `supabase gen types typescript --local`).
// Do not edit by hand — committed only as a placeholder until the local DB is running.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

type EventTypeEnum =
  | "devfest"
  | "build_with_ai"
  | "google_io"
  | "meetup"
  | "tech_talk"
  | "conference"
  | "workshop"
  | "hackathon";

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "12";
  };
  public: {
    Tables: {
      events: {
        Row: {
          id: string;
          slug: string;
          name: string;
          type: EventTypeEnum;
          year: number;
          status: "draft" | "published" | "live" | "closed";
          language_mode: "es" | "en" | "bilingual";
          start_at: string;
          end_at: string;
          timezone: string;
          venue_name: string | null;
          venue_address: string | null;
          venue_map_url: string | null;
          ticket_url: string | null;
          pre_checkin_deadline: string | null;
          leaderboard_enabled: boolean;
          theme_key: string;
          summary_es: string | null;
          summary_en: string | null;
          expected_attendance: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          type: EventTypeEnum;
          year: number;
          status?: "draft" | "published" | "live" | "closed";
          language_mode?: "es" | "en" | "bilingual";
          start_at: string;
          end_at: string;
          timezone?: string;
          venue_name?: string | null;
          venue_address?: string | null;
          venue_map_url?: string | null;
          ticket_url?: string | null;
          pre_checkin_deadline?: string | null;
          leaderboard_enabled?: boolean;
          theme_key?: string;
          summary_es?: string | null;
          summary_en?: string | null;
          expected_attendance?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["events"]["Insert"]>;
        Relationships: [];
      };
      event_content: {
        Row: {
          event_id: string;
          hero: Json;
          agenda: Json;
          speakers: Json;
          sponsors: Json;
          gallery: Json;
          faq: Json;
          updated_at: string;
        };
        Insert: {
          event_id: string;
          hero?: Json;
          agenda?: Json;
          speakers?: Json;
          sponsors?: Json;
          gallery?: Json;
          faq?: Json;
          updated_at?: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["event_content"]["Insert"]
        >;
        Relationships: [
          {
            foreignKeyName: "event_content_event_id_fkey";
            columns: ["event_id"];
            isOneToOne: true;
            referencedRelation: "events";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: Record<never, never>;
    Functions: Record<never, never>;
    Enums: {
      event_type: EventTypeEnum;
      event_status: "draft" | "published" | "live" | "closed";
      language_mode: "es" | "en" | "bilingual";
    };
    CompositeTypes: Record<never, never>;
  };
};
